### ISSUE TITLE
Cookie nya erorr,padahal cookie gw udh bener tpi pas di masukin ke script tulisannya gini      COOKIES INVALID 

### ISSUE THREAD

**Issue by HFZ-33** [SoraDev-ID/SORADEV#1]

**Comment by SoraDev-ID** [comment]
Next update broo

Pada tanggal Sab, 18 Jun 2022 1.39 PM, HFZ-33 ***@***.***>
menulis:

**Comment by SoraDev-ID** [comment]
use a new account. or use extension from kiwi browser extension name cookie dough
